gms/urls.py
#-*- encoding:utf-8 -*-
from django.conf.urls import patterns, include, url
from xadmin.views import login_page

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', login_page),
    url(r'^xadmin/', include('xadmin.urls', namespace='xadmin')),
    url(r'^repository/', include('repository.urls', namespace='repository')),

)

repository/urls.py
from django.conf.urls import url, patterns
from views.view_repository import *

urlpatterns = patterns('',

    url(r'^repository_list/$', repository_list, name='repository_list'),
    url(r'^add_repository/$', add_repository, name='add_repository'),
    url(r'^repository_main/(?P<repo_id>\d+)$', repository_main, name='repository_main'),
    url(r'^repository_file_content/(?P<repo_id>\d+)$', repository_file_content, name='repository_file_content'),
    url(r'^reference_log/(?P<repo_id>\d+)$', reference_log, name='reference_log'),
    url(r'^show_commit/(?P<repo_id>\d+)$', show_commit, name='show_commit'),
)

xadmin/urls.py
#-*- encoding:utf-8 -*-
__author__ = 'changjie.fan' '15-3-14'

from django.conf.urls import url, patterns

from xadmin.views import login_page, sys_login, sys_logout, sys_setting_page

urlpatterns = patterns('',
    url(r'^sys_login/$', sys_login, name='sys_login'),
    url(r'^sys_setting/$', sys_setting_page, name='sys_setting_page'),
    url(r'^sys_logout/$', sys_logout, name='sys_logout'),
)

repository/models.py
#-*- encoding:utf-8 -*-
#
#create date: 2015-03-17
#author: roy
#git repository manager database model
#

from django.db import models


class Repository(models.Model):

    name = models.CharField(max_length=300)
    path = models.CharField(max_length=500)
    active = models.BooleanField(default=True)
    created_date = models.DateTimeField()
    description = models.CharField(max_length=500)

    def __unicode__(self):
        return u"%s" % self.name

    class Meta:
        db_table = 'repository_repository'

xadmin/models.py
#-*- encoding:utf-8 -*-
from django.db import models

# Create your models here.

repository/views/view_repository.py
#-*- encoding:utf-8 -*-
#
#create date: 2015-03-17
#author: roy
#git repository manager view
#
import os

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from git import *

from ..models import Repository
from gms.settings import GIT_REPOSITORIES
from gms.utils import get_current_time
from repository.lib.repo_options import RepoOptions
from repository.lib.utils import path_to_url


def repository_list(request):
    """all repository list"""

    repositories = [(index+1, item) for index, item in enumerate(Repository.objects.filter(active=True).order_by('-created_date'))]
    return render(request, 'repository/repository_page.html',
        {'repositories': repositories})


def repository_main(request, repo_id):
    """显示仓库目录信息"""

    reference_name = request.GET.get('reference_name', '')
    file_path = request.GET.get('file_path', '')

    repository = Repository.objects.get(id=repo_id)
    repo_option = RepoOptions(repository.path)
    repo = repo_option.repo

    last_commit = ''

    if not reference_name and repo.references:
        reference_name = repo.references[0].name
    #print "file_path:%s" % file_path
    if reference_name:
        last_commit = repo.commit(reference_name)

    result = repo_option.ls_tree(reference_name, file_path)

    request.session['repository_id'] = repo_id
    request.session['repository_name'] = repository.name

    href = '/repository/repository_main/%s?reference_name=%s' % (repo_id, reference_name)
    current_path = path_to_url(file_path, href)
    if current_path:
        current_path = '/' + current_path
    current_path = '<a href="/repository/repository_main/%s">%s</a>' % (repository.id, repository.name) + current_path

    commit_count = repo_option.reference_commit_count(reference_name)

    return render(request, 'repository/repository.html', {'repository': repository, 'references': repo.references,
        'current_reference': reference_name, 'last_commit': last_commit, 'file_list': result,
        'current_path': current_path, 'commit_count': commit_count})


def add_repository(request):
    """create new repository"""

    repository_name = request.POST.get('repository_name', '')
    repository_description = request.POST.get('repository_description', '')

    repository_path = os.path.join(GIT_REPOSITORIES, repository_name)
    if not repository_path.endswith('.git'):
        repository_path = ''.join([repository_path, '.git'])
    os.makedirs(repository_path)
    repo = Repo.init(repository_path, bare=True)

    repository = Repository(name=repository_name, path=repository_path, created_date=get_current_time(), description=repository_description)
    repository.save()

    return HttpResponseRedirect('/repository/repository_list/')


def repository_file_content(request, repo_id):
    """show repository file content"""

    revision = request.GET.get('revision', '')
    file_path = request.GET.get('file_path', '')
    repository = Repository.objects.get(id=repo_id)

    repo_option = RepoOptions(repository.path)
    file_content = repo_option.show_file_content(revision, file_path).replace('\n', '<br>')

    return render(request, 'repository/file_content.html', {'repository':repository, 'file_path': file_path,'file_content': file_content})


def reference_log(request, repo_id):
    """show refernce all log"""

    reference_name = request.GET.get('reference_name', '')

    repository = Repository.objects.get(id=repo_id)

    repo_option = RepoOptions(repository.path)
    status, all_commit = repo_option.commits(reference_name)

    commit_list = []
    if status:
        commit_date_list = []
        for commit in all_commit:
            if commit.committered_date not in commit_date_list:
                commit_date_list.append(commit.committered_date)

        for commit_date in commit_date_list:
            commit_obj = []
            for commit in all_commit:
                if commit.committered_date == commit_date:
                    commit_obj.append(commit)

            commit_list.append((commit_date, commit_obj))


    return render(request, 'repository/repository_log.html', {'repository': repository, 'all_commit': commit_list})


def show_commit(request, repo_id):
    """show commit detail info"""

    short_commit_id = request.GET.get('commit_id', '')
    repository = Repository.objects.get(id=repo_id)

    repo_option = RepoOptions(repository.path)

    lines = repo_option.show_object(short_commit_id).split('\n')

    is_merge = False
    commit_info =[]
    for line in lines:

        if line.startswith('+++'):
             commit_info.append(line+'<br><br>')
        elif line.startswith('+'):
             line = '<span style="background-color: #dbffdb;border-color: #c1e9c1;">%s</span>' % line
             commit_info.append(line)
        elif line.startswith('-'):
             line = '<span style=" background-color: #ffdddd;border-color: #f1c0c0;">%s</span>' % line
             commit_info.append(line)
        else:
            commit_info.append(line)

        if line.strip().startswith('Merge'):
            is_merge = True
    if is_merge:
        commit_info.append('<h4>合并Commit</h4>')

    return render(request, 'repository/commit.html', {'repository': repository, 'commit_info': commit_info})

xadmin/views.py
#-*- encoding:utf-8 -*-
__author__ = 'changjie.fan' '15-3-14'

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.contrib.auth import authenticate, logout as user_logout, login as user_login
from django.contrib.auth.models import User


def login_page(request):
    """系统登录页面"""
    return render(request, 'xadmin/login.html')


def sys_login(request):
    """用户登录"""

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    #remember_me = request.POST.get('remember_me', '')

    user = authenticate(username=username, password=password)
    if user:
        user_login(request, user)
        #print username
        return render(request, 'xadmin/index.html', {'username': username})
    else:
        user = User.objects.filter(username=username)
        if user:
            return render(request, 'xadmin/login.html', {'error_message': '密码不正确!'})
        else:
            return render(request, 'xadmin/login.html', {'error_message': '用户名不存在!'})


def sys_logout(request):
    """注销系统"""

    user_logout(request)
    return render(request, 'xadmin/login.html')


def sys_setting_page(request):
    """系统设置页面"""

    return render(request, 'xadmin/setting.html')

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Joychao <joy@joychao.cc>">

    <link class="bootstrap library" rel="stylesheet" type="text/css" href="/static/lib/bootstrap/css/bootstrap.min.css">
    <script class="bootstrap library" src="/static/lib/jquery/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script class="bootstrap library" src="/static/lib/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }
        .loginBox {
            width: 420px;
            height: 260px;
            padding: 0 20px;
            border: 1px solid #fff;
            color: #000;
            margin-top: 40px;
            border-radius: 8px;
            background: white;
            box-shadow: 0 0 15px #222;
            background: -moz-linear-gradient(top, #fff, #efefef 8%);
            background: -webkit-gradient(linear, 0 0, 0 100%, from(#f6f6f6), to(#f4f4f4));
            font: 11px/1.5em 'Microsoft YaHei';
            position: absolute;
            left: 50%;
            top: 45%;
            margin-left: -210px;
            margin-top: -115px;
        }

        .loginBox h2 {
            height: 45px;
            font-size: 20px;
            font-weight: normal;
        }

        .loginBox .left {
            border-right: 1px solid #ccc;
            height: 100%;
            padding-right: 20px;
        }
    </style>
    {% block head %}{% endblock %}
</head>
<body>
    {% block menu_bar %}{% endblock %}
    {% block body %}{% endblock %}
</body>
{% block script %}{% endblock %}
</html>

templates/repository/commit.html
{% extends "xadmin/my_base.html" %}


{% block body%}
<div class="container" style="width:90%">
    <ol class="breadcrumb">
        <li><a href="{% url 'repository:repository_main' session.repository_id%}">{{session.repository_name}}</a></li>
        <li><a href="">{{ file_path }}</a></li>
    </ol>

    {% for line in commit_info %}
        {{ line|safe }}<br>
    {% endfor %}

</div>
{% endblock %}

templates/repository/file_content.html
{% extends "xadmin/my_base.html" %}
{% extends "xadmin/my_base.html" %}


{% block body%}
<div class="container" style="width:90%">
    <ol class="breadcrumb">
        <li><a href="{% url 'repository:repository_main' session.repository_id%}">{{session.repository_name}}</a></li>
        <li><a href="">{{ file_path }}</a></li>
    </ol>

    {{ file_content|safe}}

</div>
{% endblock %}

templates/repository/repository.html
{% extends "xadmin/my_base.html" %}


{% block body%}
<div class="container" style="width:90%">
    <div class="row">
        <div class="col-sm-10">
            <a href='{% url "repository:reference_log" repository.id %}?reference_name={{current_reference}}'>
                <span class="glyphicon glyphicon-time">{{ commit_count }} Commits</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <select style="width:40%" onchange="reference_change(value)">
                {% for reference in references %}
                    {% if current_reference == reference.name %}
                        <option value="{{reference.name}}" selected="">{{reference.name}}</option>
                    {% else %}
                        <option value="{{reference.name}}">{{reference.name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
            {{current_path|safe}}
        </div>
        <div class="col-sm-2">{{ last_commit}}</div>
    </div>
    <div class="">
        <table class="table table-hover">
            <thead>
                <th style="width:20%"></th>
                <th style="width:65%"></th>
                <th style="width:15%"></th>
            </thead>
            <tbody>
                {% for file in file_list%}
                    <tr>
                        {% if file.type == 'tree' %}
                            <td class="glyphicon glyphicon-folder-close">
                                <a href='{% url "repository:repository_main" repository.id %}?reference_name={{current_reference}}&file_path={{ file.path }}'>
                                    {{file.name}}
                                </a>
                            </td>
                        {% else %}
                            <td class="glyphicon glyphicon-file">
                                <a href='{% url "repository:repository_file_content" repository.id %}?revision={{current_reference}}&file_path={{file.path}}'>
                                    {{file.name}}
                                </a>
                            </td>
                        {% endif %}
                        <td>{{file.message}}</td>
                        <td>{{file.committed_date}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    function reference_change(value){
        window.location.href='{% url "repository:repository_main" repository.id %}?reference_name='+value;
    }
</script>
{% endblock %}

templates/repository/repository_log.html
{% extends "xadmin/my_base.html" %}


{% block body%}
<div class="container" style="width:90%">
    <ol class="breadcrumb">
        <li>Git Repo:
            <a href="{% url 'repository:repository_main' session.repository_id%}">
                {{session.repository_name}}
            </a>
        </li>
    </ol>
    <table class="table table-hover">
        {% for commit_date, commits in all_commit %}
            <tr>
                <td colspan=4>{{ commit_date }}</td>
            </tr>
            {% for commit in commits %}
                <tr class="active">
                    <td>{{ commit.commit_id }}</td>
                    <td>
                        <a href="{% url 'repository:show_commit' repository.id %}?commit_id={{commit.commit_id}}">
                            {{ commit.title }}
                        </a>
                    </td>
                    <td>{{ commit.committer_name}}</td>
                    <td>{{ comit.commit_id }}</td>
            </tr>
            {% endfor %}
        {% endfor %}

    </table>


</div>
{% endblock %}

templates/repository/repository_page.html
{% extends "xadmin/my_base.html" %}
{% block body%}
<div class="container">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#newRepositoryModal">
        添加仓库
    </button>

    <table class="table table-hover">
        <thead>
            <th style="width:1%"></th>
            <th style="width:30%"></th>
            <th style="width:60%"></th>
        </thead>
        <tbody>
            {% for index, repo in repositories %}
            <tr>
                <td>{{index}}</td>
                <td><a href="{% url 'repository:repository_main' repo.id%}">{{repo.name}}</a></td>
                <td>{{repo.path}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Modal -->
    <div class="modal fade" id="newRepositoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">创建新仓库</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" method="POST" id="new_repository_form" action="{% url 'repository:add_repository' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="repository_name" class="col-sm-2 control-label">仓库名称</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="repository_name" name="repository_name" autofocus
                                    placheholder="新增仓库的名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="repository_description" class="col-sm-2 control-label">仓库描述</label>
                            <div class="col-sm-10">
                                <textarea rows="7" class="form-control" id="repository_description" name="repository_description" style="resize:none;"
                                    placheholder="仓库的具体描述信息">
                                </textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary glyphicon glyphicon-remove-circle" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary glyphicon glyphicon-ok-circle" onclick="form_submit()">提交</button>
                </div>
            </div>
        </div>
    </div>


</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
function form_submit(){
    $("#new_repository_form").submit();
}

</script>
{% endblock %}

templates/xadmin/index.html
{% extends "xadmin/my_base.html" %}
{% block body %}


{% endblock %}

templates/xadmin/login.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <div class="loginBox row">
        <div class="col-lg-7 left">
             <h2>系统登录</h2>
             <form method="POST" action="{% url 'xadmin:sys_login' %}">
                {% csrf_token %}
                {% if error_message %}
                    <label style="color:red">{{ error_message }}</label>
                {% endif %}
                <p><input class="form-control" type="text" name="username" required ></p>
                <p><input class="form-control" type="password" name="password" required ></p>
                <input type="submit" value=" 登录 " class="btn btn-primary">
            </form>
       </div>
       <div class="col-lg-5">
           <h2>没有帐户？</h2>
       <div>
           <p>这里有一段文字啊，很多的文字啊，太多太多的文字了，主要可以介绍介绍注册的好处和公司或者项目概况。。。</p>
           <p><input type="button" value=" 注册 " class="btn"></p>
       </div>
    </div>
</div>
<!-- /loginBox -->
</div>
<!-- /container -->
{% endblock %}

templates/xadmin/my_base.html
{% extends "base.html" %}
{% block menu_bar%}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-navbar-menu">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">GMS</a>
    </div>

    <div class="collapse navbar-collapse" id="my-navbar-menu">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/repository/repository_list/">仓库管理<span class="sr-only">(current)</span></a></li>
      </ul>
       <ul class="nav navbar-nav">
        <li><a href="#">用户管理<span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="#">权限管理<span class="sr-only">(current)</span></a></li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            {{username}}<span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'xadmin:sys_setting_page' %}" class="active">设置</a></li>
            <li><a href="{% url 'xadmin:sys_logout' %}">注销</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

{% block script %}
{% endblock%}

templates/xadmin/setting.html
{% extends "xadmin/base.html" %}
{% block body %}
<form class="form-horizontal">
  <div class="form-group">
    <label for="repositories" class="col-sm-2 control-label">Git仓库根目录</label>
    <div class="col-sm-3">
      <input type="text" class="form-control" name="repositories" placeholder="绝度路径">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
{% endblock %}